force-app/main/default/objects/Suggestion__c/Suggestion__c.object-meta.xml
<CustomObject>
    <label>Suggestion</label>
    <nameField>
        <label>Suggestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suggestions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

lwcbrillio/force-app/main/default/objects/Suggestion__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Suggestions</relationshipLabel>
    <relationshipName>Suggestions</relationshipName>
    <type>Lookup</type>
</CustomField>

lwcbrillio/force-app/main/default/objects/Suggestion__c/fields/ChannelType__c.field-meta.xml
<CustomField>
    <fullName>ChannelType__c</fullName>
    <label>Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suggestion__c/fields/Description_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Description_Rich_Text__c</fullName>
    <label>Description Rich Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

lwcbrillio/force-app/main/default/objects/Suggestion__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Suggestion__c/fields/SuggestedDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>SuggestedDateAndTime__c</fullName>
    <label>Suggested Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Suggestion__c/fields/UserAction__c.field-meta.xml
<CustomField>
    <fullName>UserAction__c</fullName>
    <label>User Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Mark as Done</fullName>
            </value>
            <value>
                <fullName>Emailed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SuggestionsController.cls
public with sharing class SuggestionsController {
    
    
    @AuraEnabled(cacheable=true)
    public static list<Suggestion__c> getSuggestions() {
        list<Suggestion__c> suggestionsList = [SELECT id, Account__c, Account__r.Name, Rank__c, Status__c, Subject__c, SuggestedDateAndTime__c, UserAction__c, CreatedDate, Description_Rich_Text__c, ChannelType__c FROM Suggestion__c where Status__c = false ORDER BY CreatedDate DESC LIMIT 3]; 
        system.debug('suggestionsList '+suggestionsList);
        return suggestionsList;
    }

    @AuraEnabled(cacheable=true)
    public static list<Suggestion__c> getMoreSuggestions(Integer queryOffset){
        list<Suggestion__c> suggestionsList = [SELECT id, Account__c, Account__r.Name, Rank__c, Status__c, Subject__c, SuggestedDateAndTime__c, UserAction__c, CreatedDate, Description_Rich_Text__c, ChannelType__c FROM Suggestion__c where Status__c = false ORDER BY CreatedDate DESC LIMIT 3 OFFSET :queryOffset];  
        return suggestionsList;
    }

    public class suggestionRecordResult{
        @AuraEnabled
        public Integer totalRecordCount { get; set; }

        @AuraEnabled
        public List<Suggestion__c> suggestionRecords {get;set;}
    }

    @AuraEnabled(cacheable=true)
    public static suggestionRecordResult getSuggestionRecords(Integer queryOffset, String filterkey){

        suggestionRecordResult recordResult = new suggestionRecordResult();

        String countQuery = 'SELECT count() FROM Suggestion__c ';

        String query = 'SELECT id, Account__c, Account__r.Name, Rank__c, Status__c, Subject__c,' + 'SuggestedDateAndTime__c, UserAction__c, CreatedDate, Description_Rich_Text__c, ChannelType__c FROM Suggestion__c ';  

        if (!String.isBlank(filterkey)) {
            query = query + 'WHERE ChannelType__c =: filterkey AND Status__c = false';
            countQuery = countQuery + 'WHERE ChannelType__c =: filterkey AND Status__c = false';
        } else {
            query = query + 'WHERE Status__c = false';
        }

        query = query + ' ORDER BY CreatedDate DESC LIMIT 3 OFFSET :queryOffset';

        system.debug('query '+query);
        recordResult.suggestionRecords = Database.query(query);
        recordResult.totalRecordCount =(Integer) Database.countQuery(countQuery); 

        return recordResult;
    }

    @AuraEnabled
    public static void acceptSchedule(Suggestion__c sugRecord, String userAction){
        if(userAction == 'Accept'){
            Suggestion__c updatedRecord = new Suggestion__c(Id = sugRecord.Id, 
                                                            Status__c = true, 
                                                            UserAction__c = 'Accepted'); 
            update updatedRecord; 
            Event e = new Event(Type = sugRecord.ChannelType__c, 
                                Description = sugRecord.Subject__c, 
                                WhatId = sugRecord.Account__c, 
                                OwnerId = UserInfo.getUserId(), 
                                Suggestion__c = sugRecord.Id, 
                                DurationInMinutes = 30,
                                ActivityDateTime = sugRecord.SuggestedDateAndTime__c); 
            insert e;
        }
        /*else if(userAction == 'Dismiss'){
            Suggestion__c updatedRecord = new Suggestion__c(Id = sugRecord.Id, 
                                                        Status__c = true, 
                                                        UserAction__c = 'Dismissed'); 
        }*/
    }

    @AuraEnabled
    public static void dismissSchedule(Suggestion__c sugtnRecord){
        Suggestion__c updatedRecord = new Suggestion__c(Id = sugtnRecord.Id, 
                                                        Status__c = true, 
                                                        UserAction__c = 'Dismissed'); 
        update updatedRecord; 
    }
}